package com.mtgebay.app.scan

import org.junit.Assert.assertEquals
import org.junit.Test
import java.nio.ByteBuffer
import java.nio.ByteOrder

/**
 * Golden-fixture tests proving [Phasher.phash] matches Python `imagehash.phash`
 * bit-for-bit. Fixtures are generated by `phash-db-generator/save_fixtures.py`.
 *
 * Each fixture under `src/test/resources/phash-fixtures/{NN}/`:
 *  - `grayscale.bin`  1024 little-endian float64 values (row-major 32x32, uint8 cast to f64)
 *  - `expected.txt`   "0x" + 16 hex chars (the imagehash.phash u64)
 *  - `meta.txt`       human-readable card metadata for debugging
 */
class PhasherTest {

    @Test fun fixture00() = checkFixture(0)
    @Test fun fixture01() = checkFixture(1)
    @Test fun fixture02() = checkFixture(2)
    @Test fun fixture03() = checkFixture(3)
    @Test fun fixture04() = checkFixture(4)
    @Test fun fixture05() = checkFixture(5)
    @Test fun fixture06() = checkFixture(6)
    @Test fun fixture07() = checkFixture(7)
    @Test fun fixture08() = checkFixture(8)
    @Test fun fixture09() = checkFixture(9)

    @Test
    fun rejectsWrongSize() {
        try {
            Phasher.phash(DoubleArray(100))
            error("Should have thrown for wrong-size input")
        } catch (e: IllegalArgumentException) {
            // expected
        }
    }

    private fun checkFixture(index: Int) {
        val name = "%02d".format(index)
        val grayscale = loadGrayscale(name)
        val expected = loadExpectedHash(name)
        val actual = Phasher.phash(grayscale)
        val meta = runCatching { readResource("/phash-fixtures/$name/meta.txt") }
            .map { String(it) }
            .getOrDefault("(no meta)")
        assertEquals(
            "Fixture $name pHash mismatch.\n" +
                "  expected = 0x${expected.toULong().toString(16).padStart(16, '0')}\n" +
                "  actual   = 0x${actual.toULong().toString(16).padStart(16, '0')}\n" +
                "  meta:\n$meta",
            expected,
            actual,
        )
    }

    private fun loadGrayscale(name: String): DoubleArray {
        val bytes = readResource("/phash-fixtures/$name/grayscale.bin")
        require(bytes.size == 1024 * 8) {
            "Expected 8192-byte grayscale.bin for fixture $name, got ${bytes.size}"
        }
        val buf = ByteBuffer.wrap(bytes).order(ByteOrder.LITTLE_ENDIAN)
        return DoubleArray(1024) { buf.double }
    }

    private fun loadExpectedHash(name: String): Long {
        val raw = String(readResource("/phash-fixtures/$name/expected.txt")).trim()
        require(raw.startsWith("0x")) { "Expected '0x...' in fixture $name expected.txt, got: $raw" }
        return java.lang.Long.parseUnsignedLong(raw.removePrefix("0x"), 16)
    }

    private fun readResource(path: String): ByteArray =
        javaClass.getResourceAsStream(path)
            ?.use { it.readBytes() }
            ?: error("Resource not found: $path")
}
