package com.mtgebay.app.scan

import java.io.IOException
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.channels.FileChannel
import java.nio.file.Path
import java.nio.file.StandardOpenOption
import java.util.PriorityQueue
import java.util.UUID

/**
 * Reader over the `phash.bin` perceptual-hash database generated by
 * `phash-db-generator/generate.py`. Pure JVM — no Android imports. The Android
 * side will memory-map the asset and hand its `ByteBuffer` to [fromBuffer].
 *
 * Binary layout (little-endian):
 *
 * ```
 * Header  : "MTGP" (4 B) | u16 version=1 | u32 record_count          (10 B)
 * Record  : u64 phash | 16 B scryfall_id (UUID raw) | u8 finishes
 *         | 8 B set_code (UTF-8, NUL-pad) | 8 B collector_number     (41 B)
 * ```
 *
 * Records are sorted by `phash` ascending in the file, but Hamming distance is
 * not monotonic in numeric distance, so [lookup] does a brute-force scan rather
 * than binary search. At ~97k records and one XOR+popcount per record, a full
 * scan is well under a millisecond on a recent device.
 */
class PhashDb private constructor(
    private val buffer: ByteBuffer,
    val recordCount: Int,
) {

    /**
     * Find the [topN] records whose pHash is closest (in Hamming distance) to
     * [hash], filtering out anything beyond [maxHamming] bits of difference.
     *
     * Returns hits sorted by ascending distance. Empty if no record is within
     * [maxHamming].
     */
    fun lookup(
        hash: Long,
        maxHamming: Int = DEFAULT_MAX_HAMMING,
        topN: Int = DEFAULT_TOP_N,
    ): List<PhashHit> {
        require(topN > 0) { "topN must be positive, got $topN" }
        require(maxHamming in 0..64) { "maxHamming must be 0..64, got $maxHamming" }

        // Max-heap by distance: head holds the worst of the current top-N so we
        // can compare new candidates without resorting.
        val heap = PriorityQueue<PhashHit>(topN) { a, b -> b.distance.compareTo(a.distance) }

        for (i in 0 until recordCount) {
            val offset = HEADER_SIZE + i * RECORD_SIZE
            val recordPhash = buffer.getLong(offset)
            val dist = (recordPhash xor hash).countOneBits()
            if (dist > maxHamming) continue

            if (heap.size < topN) {
                heap.offer(readHit(i, offset, recordPhash, dist))
            } else {
                // peek() is non-null here because heap.size == topN >= 1.
                val worst = heap.peek()!!
                if (dist < worst.distance) {
                    heap.poll()
                    heap.offer(readHit(i, offset, recordPhash, dist))
                }
            }
        }

        // Drain heap into a distance-ascending list. poll() is non-null while size > 0.
        val out = ArrayList<PhashHit>(heap.size)
        while (heap.isNotEmpty()) out.add(heap.poll()!!)
        out.sortBy { it.distance }
        return out
    }

    private fun readHit(index: Int, offset: Int, phash: Long, distance: Int): PhashHit {
        // Layout at offset:
        //   +0  : u64 phash               (already read)
        //   +8  : 16 B scryfall_id (UUID raw bytes, big-endian for hi/lo per RFC 4122)
        //   +24 : u8  finishes_mask
        //   +25 : 8 B set_code (UTF-8, NUL-padded)
        //   +33 : 8 B collector_number (UTF-8, NUL-padded)
        // Use absolute gets so the buffer is safe to share across threads.
        val uuidHi = buffer.getLong(offset + 8)
        val uuidLo = buffer.getLong(offset + 16)
        // UUID raw bytes are big-endian; ByteBuffer is little-endian for our format.
        // Convert by reversing the high/low 64-bit halves byte-wise.
        val scryfallId = UUID(java.lang.Long.reverseBytes(uuidHi), java.lang.Long.reverseBytes(uuidLo))

        val finishesMask = buffer.get(offset + 24).toInt() and 0xFF
        val setCode = readUtf8Field(offset + 25, 8)
        val collectorNumber = readUtf8Field(offset + 33, 8)

        return PhashHit(
            index = index,
            phash = phash,
            scryfallId = scryfallId,
            finishesMask = finishesMask,
            setCode = setCode,
            collectorNumber = collectorNumber,
            distance = distance,
        )
    }

    private fun readUtf8Field(offset: Int, length: Int): String {
        val bytes = ByteArray(length)
        for (i in 0 until length) bytes[i] = buffer.get(offset + i)
        var end = length
        while (end > 0 && bytes[end - 1] == 0.toByte()) end--
        return String(bytes, 0, end, Charsets.UTF_8)
    }

    companion object {
        const val DEFAULT_MAX_HAMMING: Int = 12
        const val DEFAULT_TOP_N: Int = 3

        private const val HEADER_SIZE = 10
        private const val RECORD_SIZE = 41
        private const val MAGIC_BYTE_0: Byte = 'M'.code.toByte()
        private const val MAGIC_BYTE_1: Byte = 'T'.code.toByte()
        private const val MAGIC_BYTE_2: Byte = 'G'.code.toByte()
        private const val MAGIC_BYTE_3: Byte = 'P'.code.toByte()
        private const val SUPPORTED_VERSION: Short = 1

        /**
         * Parse a phash.bin from an in-memory [ByteArray]. Useful for tests and
         * for asset-backed buffers wrapped at the call site.
         */
        fun fromBytes(bytes: ByteArray): PhashDb =
            fromBuffer(ByteBuffer.wrap(bytes))

        /**
         * Parse a phash.bin from a [ByteBuffer]. The buffer's byte order is
         * forced to little-endian regardless of input. All reads use absolute
         * positioning, so the returned [PhashDb] is safe to share across threads.
         */
        fun fromBuffer(buffer: ByteBuffer): PhashDb {
            val view = buffer.duplicate().order(ByteOrder.LITTLE_ENDIAN)
            check(view.remaining() >= HEADER_SIZE) {
                "phash.bin too small for header: ${view.remaining()} bytes"
            }
            val base = view.position()
            check(
                view.get(base) == MAGIC_BYTE_0 &&
                    view.get(base + 1) == MAGIC_BYTE_1 &&
                    view.get(base + 2) == MAGIC_BYTE_2 &&
                    view.get(base + 3) == MAGIC_BYTE_3
            ) { "phash.bin magic mismatch (expected MTGP)" }
            val version = view.getShort(base + 4)
            check(version == SUPPORTED_VERSION) {
                "phash.bin version $version not supported (expected $SUPPORTED_VERSION)"
            }
            val count = view.getInt(base + 6)
            val expectedSize = HEADER_SIZE + count.toLong() * RECORD_SIZE
            val actualSize = view.remaining().toLong()
            check(actualSize == expectedSize) {
                "phash.bin size mismatch: expected $expectedSize bytes for $count records, got $actualSize"
            }
            // Slice off the base so all internal reads are relative to 0.
            val sliced = if (base == 0) view else view.slice().order(ByteOrder.LITTLE_ENDIAN)
            return PhashDb(sliced, count)
        }

        /**
         * Memory-map a phash.bin file from disk read-only. The returned [PhashDb]
         * holds a `MappedByteBuffer`; the OS handles paging. Caller does not need
         * to close anything explicitly.
         */
        @Throws(IOException::class)
        fun fromFile(path: Path): PhashDb {
            FileChannel.open(path, StandardOpenOption.READ).use { channel ->
                val mapped = channel.map(FileChannel.MapMode.READ_ONLY, 0, channel.size())
                return fromBuffer(mapped)
            }
        }
    }
}

/**
 * A single search result. [distance] is the Hamming distance between the query
 * pHash and this record's pHash; smaller is closer.
 */
data class PhashHit(
    val index: Int,
    val phash: Long,
    val scryfallId: UUID,
    val finishesMask: Int,
    val setCode: String,
    val collectorNumber: String,
    val distance: Int,
) {
    /** True iff the record exposes a non-foil printing. */
    val hasNonFoil: Boolean get() = (finishesMask and 0b0001) != 0

    /** True iff the record exposes a foil printing (regular foil). */
    val hasFoil: Boolean get() = (finishesMask and 0b0010) != 0

    /** True iff the record exposes etched foil. */
    val hasEtched: Boolean get() = (finishesMask and 0b0100) != 0

    /** True iff the record exposes glossy foil. */
    val hasGlossy: Boolean get() = (finishesMask and 0b1000) != 0
}
