package com.mtgebay.app.scan

import kotlin.math.PI
import kotlin.math.cos

/**
 * Pure-Kotlin perceptual hash (pHash). Bit-for-bit equivalent to Python's
 * `imagehash.phash(img, hash_size=8)` from imagehash 4.3.1 over a 32x32
 * grayscale matrix.
 *
 * Algorithm (matches scipy.fftpack.dct default = type-II, norm=None):
 *   1. 2D DCT-II of the 32x32 input (separable: column-wise then row-wise).
 *   2. Take the top-left 8x8 = 64 low-frequency coefficients.
 *   3. Compute the median of those 64 values (mean of the two middle when sorted).
 *   4. Bit `i` (row-major within the 8x8) = 1 if coefficient > median, else 0.
 *   5. Pack: result bit `i` corresponds to `1L shl i`.
 *
 * This object does **not** perform the Bitmap → grayscale → Lanczos resize; the
 * caller supplies the pre-resized matrix. The BitmapPhasher wrapper (Phase 2c)
 * handles the resize once OpenCV is wired in.
 *
 * Verified against ten golden fixtures generated by `phash-db-generator/save_fixtures.py`;
 * see `PhasherTest` in the unit-test source set.
 */
object Phasher {

    private const val IMG_SIZE = 32
    private const val HASH_SIZE = 8
    private const val LOWFREQ_LEN = HASH_SIZE * HASH_SIZE  // 64

    /** Precomputed cosine table: `COS_TABLE[k][n] = cos(pi*(2n+1)*k/(2N))`. */
    private val COS_TABLE: Array<DoubleArray> = Array(IMG_SIZE) { k ->
        DoubleArray(IMG_SIZE) { n -> cos(PI * (2 * n + 1) * k / (2.0 * IMG_SIZE)) }
    }

    /** 1D unnormalized DCT-II: `y[k] = 2 * sum_n x[n] * cos(pi*(2n+1)*k/(2N))`. */
    private fun dct1d(input: DoubleArray, output: DoubleArray) {
        for (k in 0 until IMG_SIZE) {
            val row = COS_TABLE[k]
            var sum = 0.0
            for (n in 0 until IMG_SIZE) {
                sum += input[n] * row[n]
            }
            output[k] = 2.0 * sum
        }
    }

    /**
     * Compute the 64-bit pHash of a row-major 32x32 grayscale matrix.
     *
     * @param grayscale32x32 length 1024, row-major (`row * 32 + col`). Values are
     *   typically uint8 intensities cast to Double (0.0..255.0).
     * @return the 64-bit pHash. Use `toULong().toString(16)` to print as 16 hex digits.
     */
    fun phash(grayscale32x32: DoubleArray): Long {
        require(grayscale32x32.size == IMG_SIZE * IMG_SIZE) {
            "Phasher.phash expects ${IMG_SIZE * IMG_SIZE} values, got ${grayscale32x32.size}"
        }

        // Step 1: DCT-II along axis 0 (each column independently).
        // intermediate[col][row] holds the row-th output of column col's DCT.
        val intermediate = Array(IMG_SIZE) { DoubleArray(IMG_SIZE) }
        val colIn = DoubleArray(IMG_SIZE)
        val colOut = DoubleArray(IMG_SIZE)
        for (col in 0 until IMG_SIZE) {
            for (row in 0 until IMG_SIZE) {
                colIn[row] = grayscale32x32[row * IMG_SIZE + col]
            }
            dct1d(colIn, colOut)
            for (row in 0 until IMG_SIZE) {
                intermediate[col][row] = colOut[row]
            }
        }

        // Step 2: DCT-II along axis 1 (each row of the intermediate independently).
        // We only need the top-left 8x8 of the final DCT, so compute exactly those rows
        // but the columns must be processed in full because each col input is a full row
        // (length 32) of the intermediate.
        val lowFreq = DoubleArray(LOWFREQ_LEN)
        val rowIn = DoubleArray(IMG_SIZE)
        val rowOut = DoubleArray(IMG_SIZE)
        for (row in 0 until HASH_SIZE) {
            for (col in 0 until IMG_SIZE) {
                rowIn[col] = intermediate[col][row]
            }
            dct1d(rowIn, rowOut)
            for (col in 0 until HASH_SIZE) {
                lowFreq[row * HASH_SIZE + col] = rowOut[col]
            }
        }

        // Step 3: median = mean of the two middle elements of the 64-value sort.
        val sorted = lowFreq.copyOf().also { it.sort() }
        val median = (sorted[LOWFREQ_LEN / 2 - 1] + sorted[LOWFREQ_LEN / 2]) / 2.0

        // Step 4+5: pack bits, with `bit i = 1` when `lowFreq[i] > median`.
        var bits = 0L
        for (i in 0 until LOWFREQ_LEN) {
            if (lowFreq[i] > median) bits = bits or (1L shl i)
        }
        return bits
    }
}
